### ISSUE TITLE
Create lunatic cli

### ISSUE THREAD

**Issue by Diogenesoftoronto** [lunatic-solutions/submillisecond#79]
Create a quick start cli commands to get a barebones project up and running

**Comment by tqwewe** [comment]
Since there's not really a lot of options you could change when setting up a submillisecond project, maybe it would be better if we setup a github template repository?
Or even just improve our docs for setting up a project.

The [docs.rs page](https://docs.rs/submillisecond/0.2.0-alpha0/submillisecond/#usage) has some basic steps for setting up a project.

**Comment by tqwewe** [comment]
I've created a starter repository which can be used as a template.
https://github.com/tqwewe/submillisecond-starter
